version: "3.9"

services:
  db:
    image: postgres:15
    container_name: normativa_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: normativa_transito
      POSTGRES_USER: normativa_user
      POSTGRES_PASSWORD: tu_contraseña_segura
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
