version: '3.8'

services:
  db:
    image: postgres:14
    container_name: normativa_postgres
    restart: always
    environment:
      POSTGRES_USER: normativa_user
      POSTGRES_PASSWORD: normativa_pass
      POSTGRES_DB: normativa_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - normativa_net

networks:
  normativa_net:
    driver: bridge
